// demo/react/WYSIWYGEditor.jsx
import { useCallback, useEffect, useRef } from "react";
import { WYSIWYGEditor as Editor } from "wysiwyg-editor";
import "wysiwyg-editor/dist/wysiwyg-editor.css";

/**
 * React wrapper for the WYSIWYG Editor.
 *
 * @param {object} props
 * @param {string[]}  [props.toolbar]        - toolbar items (action names or '|' for separator)
 * @param {string}    [props.placeholder]    - placeholder text
 * @param {string}    [props.initialContent] - initial HTML content
 * @param {number}    [props.minHeight]      - minimum editor height in px
 * @param {function}  [props.onChange]        - called with HTML string on every change
 * @param {function}  [props.onReady]        - called with the editor instance after mount
 * @param {string}    [props.className]      - additional CSS class for the container
 */
export default function WYSIWYGEditor({
  toolbar,
  placeholder,
  initialContent,
  minHeight,
  onChange,
  onReady,
  className,
}) {
  const containerRef = useRef(null);
  const editorRef = useRef(null);

  // Stable callback ref so the editor doesn't re-create on every render
  const onChangeRef = useRef(onChange);
  useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  const handleChange = useCallback((html) => {
    onChangeRef.current?.(html);
  }, []);

  useEffect(() => {
    if (!containerRef.current) return;

    const instance = new Editor(containerRef.current, {
      ...(toolbar && { toolbar }),
      ...(placeholder && { placeholder }),
      ...(initialContent && { initialContent }),
      ...(minHeight && { minHeight }),
      onChange: handleChange,
    });

    editorRef.current = instance;
    onReady?.(instance);

    return () => {
      instance.destroy();
      editorRef.current = null;
    };
    // Only re-create if structural props change
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [toolbar, placeholder, minHeight]);

  return <div ref={containerRef} className={className} />;
}

// editor/src/app/wysiwyg-editor.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
  ViewChild,
} from '@angular/core';
import { WYSIWYGEditor } from 'wysiwyg-editor';

@Component({
  selector: 'app-wysiwyg-editor',
  standalone: true,
  template: `<div #container [class]="cssClass"></div>`,
})
export class WYSIWYGEditorComponent implements OnInit, OnChanges, OnDestroy {
  /** Toolbar action names (use '|' for separator). */
  @Input() toolbar?: string[];

  /** Placeholder text shown when the editor is empty. */
  @Input() placeholder = '';

  /** Initial HTML content. */
  @Input() initialContent = '';

  /** Minimum editor height in px. */
  @Input() minHeight = 200;

  /** Additional CSS class for the container element. */
  @Input() cssClass = '';

  /** Emits the HTML content string on every change. */
  @Output() contentChange = new EventEmitter<string>();

  /** Emits the editor instance after initialization. */
  @Output() editorReady = new EventEmitter<WYSIWYGEditor>();

  @ViewChild('container', { static: true }) containerRef!: ElementRef<HTMLElement>;

  private editor: WYSIWYGEditor | null = null;

  ngOnInit(): void {
    this.createEditor();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (
      (changes['toolbar'] || changes['placeholder'] || changes['minHeight']) &&
      !changes['toolbar']?.firstChange
    ) {
      this.destroyEditor();
      this.createEditor();
    }
  }

  ngOnDestroy(): void {
    this.destroyEditor();
  }

  getEditor(): WYSIWYGEditor | null {
    return this.editor;
  }

  private createEditor(): void {
    this.editor = new WYSIWYGEditor(this.containerRef.nativeElement, {
      ...(this.toolbar && { toolbar: this.toolbar }),
      ...(this.placeholder && { placeholder: this.placeholder }),
      ...(this.initialContent && { initialContent: this.initialContent }),
      ...(this.minHeight && { minHeight: this.minHeight }),
      onChange: (html: string) => this.contentChange.emit(html),
    });
    this.editorReady.emit(this.editor);
  }

  private destroyEditor(): void {
    this.editor?.destroy();
    this.editor = null;
  }
}
